version: '3.9'

services:
  backend:
    platform: linux/x86_64
    container_name: cashforce_backend
    build: ./backend
    working_dir: /api
    ports:
      - 3333:3333
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5

  database:
    image: mysql:latest
    container_name: cashforce_db
    platform: linux/x86_64
    ports: 3306:3306
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DB: cashforce_v3
  restart: always
  healthcheck:
    test: [ "CMD-SHELL", "mysqladmin", "ping", "-h", "localhost" ]
    timeout: 10s
    retries: 5
  networks:
      - cashforce-db