version: '3.9'

services:
  frontend:
    platform: linux/x86_64
    container_name: cashforce-frontend
    build: ./frontend
    working_dir: /app
    ports: 5173:5173
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5173"]
      timeout: 10s
      retries: 5
    networks:
      - cashforce-app
  backend:
    platform: linux/x86_64
    container_name: cashforce-backend
    build: ./backend
    working_dir: /api
    ports:
      - 3333:3333
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3333"]
      timeout: 10s
      retries: 5
    networks:
      - cashforce-app
      - cashforce-db

  database:
    image: mysql:latest
    container_name: cashforce_db
    platform: linux/x86_64
    ports: 3306:3306
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DB: cashforce_v3
  restart: always
  healthcheck:
    test: [ "CMD-SHELL", "mysqladmin", "ping", "-h", "localhost" ]
    timeout: 10s
    retries: 5
  networks:
      - cashforce-db

networks:
  cashforce-db: {}
  cashforce-app: {}